image_topic: "/zed/left/image_raw_color" # "/zed/left/image_raw_color" # "/zed/right/image_raw_color" # "/zed/rgb/image_raw_color" # "/usb_cam/image_raw"
output_topic: "/openpose_ros/human_list"
depth_topic: "/zed/depth/depth_registered"
display_output: true
print_keypoints: false
save_original_video: false
save_openpose_video: false
original_video_file_name: ""
openpose_video_file_name: ""
video_fps: 10
depth_queue_size: 1
human_list_queue_size: 1