image_topic: "/usb_cam/image_raw"
output_topic: "/openpose_ros/human_list"
display_output: true
print_keypoints: false
save_original_video: false
save_openpose_video: false
original_video_file_name: ""
openpose_video_file_name: ""
video_fps: 10