image_topic: "/zed/left/image_raw_color"  # Asus Xtion & Orbbec Astra Pro: "/camera/rgb/image_raw" # Stereolabs ZED: "/zed/left/image_raw_color" # Standard USB webcam: "/usb_cam/image_raw"
output_topic: "/openpose_ros/human_list"
depth_topic: "/zed/depth/depth_registered" # Asus Xtion & Orbbec Astra Pro: "/camera/depth/image" # Stereolabs ZED: "/zed/depth/depth_registered"
display_output: true
print_keypoints: false
save_original_video: false
save_openpose_video: false
original_video_file_name: ""
openpose_video_file_name: ""
video_fps: 10
depth_queue_size: 1
human_list_queue_size: 1