robot_frame_coords_str_topic: "/openpose_ros_receiver/robot_frame_coords_str"
robot_frame_coords_msg_topic: "/openpose_ros_receiver/robot_frame_coords_msg"
queue_size: 1
image_frame: "/zed_left_camera_frame"
base_link_frame: "/base_link"
geometric_primitive_radius: 0.075
basic_limb_safety_radius: 0.175
geometric_primitive_radius_adaptation_limit: 0.15
basic_limb_safety_radius_adaptation_limit: 0.65
min_avg_prob: 0.25
human_body_keypoints: 25